language: node_js
node_js: node
cache:
  directories:
    - "$HOME/.npm"
script: npm run build
deploy:
  provider: s3
  access_key_id: ztDf0fCxr0eCgSIi
  secret_access_key:
     secure: rL0DOiSBdu/Xj24klpx3+4PdzEPVB5h1GzB0m2/HZ6bw2ihbR297DA8/lapzOAzQGThkaa3UTUathwxMQRu1S+l9cWosz91ER1yHp1sg8Xfy0UXDjP86pRDNX4xpuJAaMUfwIkY4UekqPuSDWxPGubMoCHB6BjPxpsH7kRLz8ePnL7T5BBrNya0vFo3DddHldwneGV6lc0OZ4ZgMbc54IwrSMlBwr0DkHJ+bcjkmdO6kjUNtP4p56kjMLpX84DIjnHu1DTOKhK+/JkhtzO/l0m0jWoFTsgfa+Q5w16Eq+eUvYkqsfcHBNeU5/tRZeIlJqWQ9B10MBqB1vJ3nhU6ddKG8vMWPNiHbLklAz1Jtr7mPU/YoWHMinH5z3a7X3r4khCAYs+o5OKqwsT+1vSoaxNRfwaVdaBOCN7PgVcC80+nTX2hWPVK7ayoJDcbHZX8btsFcC265yY2cN/z/IGpMmKt0NNV8IAQ+lasKdLhVMRfhA4zoUdWVZL78qI0GzB/4+eUZJ9vSIsrXgFHiLLyPxuAlYV5xvJSF9LeUJ4yJHtIrSUAtfFPqopP2TEmnRknNInR6ZfBpaDKbePVMnp4aMY/Fphx23t0TLBreCFW8odQxLHPfFhgm8465CDf6wJvs2Q21Gqt6ibkIR1SckcR9qiFs2TfLipv6pXBXVZN8KEc=
  bucket: mycard
  skip_cleanup: true
  local-dir: dist
  upload-dir: accounts
  endpoint: https://minio.mycard.moe:9000
