language: node_js
node_js: node
cache:
  directories:
    - "$HOME/.npm"
script: npm run build
deploy:
  provider: s3
  access_key_id: ztDf0fCxr0eCgSIi
  secret_access_key:
    secure: Ya31BLIxjtqI1wdc262kxLzuHEjaiOkq9yj+CgjoSc0gt0cG+fX9AcyarRBLKWzx3sRlqKhM0O7z6lfL6e4dP9a/3EjvXsjPhAnTnIffEDwzBgKx/Qmx5hmgofBclIQtLEYkN68OlbNcIb4g7oUAlBxNzgbpIeuztnIls/KZZWRJguvpyJMAc1US+Cky41kOUbJ1+/c6tmTN6mTWvMjfLMR0TsZTniZdpnCXzTJBd4ofsf1RzZZDwtcDXTuIMQij2QxvTv4lUUYxkvIFkq/5zLo5dToIrm9/MdqxEfcLSa1sxwGMRedFg1bA9E7wBZq19medcAXtyErnigDuJauuYhNh3xcnqAHAvk8ZShMFrMpF88WtIYxmaEYVyqiP86euV5mbpcnsOnT2fN4LEZdB9a/NVxhd+GrxSeXgv5LDUrsR2ka5tLbPvDE0C9nOf9Ok/p1lbIFY9nKkE977pqlQL1Iz0eNZvvKz7RemArEnZvUj73zPpEirp685qUAs4e8MHq4SH2P4wJ++vcEabrJNfkbnpQsrZ9+zXWohFxieuVt8RUErGP8ZlqE6S6sbzE9fxELABn3NeNxs4soZkkXDKnpUi0p7Z+tbdzvLGq+DUGMMs7p7lwA6o7yNdEZKebQFUVsts36NUnrOO5qFyg8AKIPaRWG//Cq8qE6an67lNhI=
  bucket: mycard
  skip_cleanup: true
  local-dir: dist
  upload-dir: accounts
  endpoint: https://minio.mycard.moe:9000
