language: node_js
node_js: node
cache:
  directories:
    - "$HOME/.npm"
script: npm run build
deploy:
  provider: s3
  access_key_id: ztDf0fCxr0eCgSIi
  secret_access_key:
    secure: bv+ba2hKhYkmhECHz02J/jxMUv+9gD4yPpXSbVAuRIr4Fro4ZjZrpcSVsX9KWVHNMgw+tLMYp4Ra7efbjbcJE7aHAevAp6TOMnJV+K/wjfvn2H/SNQcS+5d/LAnp6uwyKiUCTNnGtpC5CiB1mLzINe5nj2NiM8EFqGJ5dOEKmKyA3gSvNnRFFCShImUyyzQNCrsQPMtiGg5tMV0EKJq6QP1IWJkasLp3bw/6LNRjkt6VdHmR6yQI+C3ASz+ul2KxtgYlIxm1jlXkziasluMz0C09OLxCl1QtQHvDjb//P39ZgDXoDGp8VoBToMfJb+MDbBRdfye1yKlqhvFuZqCB43xb5l/AouUUthhLJGYdteaFt6VHjII6B4pqmrFPQ7eRqjHO7V/9Ntfb7Tqn91mD2xrvCwaG1rJAcZBM5dklQ7d8hjsO6spU+rk8HZ3EwD6OhmcIOF+DrT9LoTOZX2ZUr7wJSEusfxug33dB9RpXAT1vowu/ruKIo2rGtWmDkw4gcJYjIHsbPhmCr3URpmEVgraC4Ndy1pj96oQGTb2MNlfgkehfx69YFLqXa8DSNheyyH/cfFE2PvxwgfGTupqOyBDRfn5GmL+6G6/C40cCQ5RFMR16h6/3ePmfbVe69UyP8co6e6xy+RQaBlzwaSelwT/QsYk6yNAMD9TYsAW0xfE=
  bucket: mycard
  skip_cleanup: true
  local-dir: dist
  upload-dir: accounts
  endpoint: https://minio.mycard.moe:9000
